// apps/web-demo/components/SectionHeader.vue
<script setup lang="ts">
defineProps<{
  caption: string;
  title: string;
  description: string;
}>();
</script>

<template>
  <header>
    <p class="small-label">{{ caption }}</p>
    <h1 class="mt-2 text-2xl font-semibold tracking-tight">{{ title }}</h1>
    <p class="mt-2 max-w-3xl text-sm text-[var(--muted)]">{{ description }}</p>
  </header>
</template>

// apps/web-demo/app/components/section-header.tsx
type SectionHeaderProps = {
  caption: string;
  title: string;
  description?: string;
};

export function SectionHeader({ caption, title, description }: SectionHeaderProps) {
  return (
    <header className="border-b border-[var(--border)] pb-4">
      <p className="text-xs tracking-[0.2em] text-[var(--muted)] uppercase">{caption}</p>
      <h2 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h2>
      {description ? (
        <p className="mt-2 max-w-2xl text-sm text-[var(--muted)] md:text-base">{description}</p>
      ) : null}
    </header>
  );
}
