// apps/web-demo/app/routes/users.tsx
import {
  createDemoUser,
  getDemoUserById,
  listDemoUsers,
  updateDemoUserRole,
  updateDemoUserStatus,
} from "@reactiveweb/db";
import { Button } from "@reactiveweb/ui";
import { useEffect, useMemo, useState } from "react";
import { Form, Link, useNavigation, useSubmit } from "react-router";
import { Avatar } from "~/components/avatar";
import { Badge, roleBadgeVariant, statusBadgeVariant } from "~/components/badge";
import { ConfirmDialog } from "~/components/confirm-dialog";
import { EmptyState } from "~/components/empty-state";
import { InputField } from "~/components/input";
import { SectionHeader } from "~/components/section-header";
import { SelectField } from "~/components/select";
import { Skeleton } from "~/components/skeleton";
import { useToast } from "~/components/toast";
import { AUTH_PASSWORD_MIN_LENGTH, AUTH_PASSWORD_POLICY_MESSAGE } from "~/lib/auth-policy";
import { assertCanCreateUser, assertCanMutateUser } from "~/lib/authorization.server";
import {
  mapDbUserToDemoUser,
  nextRole,
  recordAuditEvent,
  requireAuthSession,
} from "~/lib/demo-state.server";
import {
  createUserInputSchema,
  type DemoUser,
  type Role,
  toRole,
  usersActionSchema,
} from "~/lib/models";
import { hashPassword } from "~/lib/password.server";
import { errorPayload } from "~/lib/server-responses";
import type { Route } from "./+types/users";

const roleOptions: { value: string; label: string }[] = [
  { value: "viewer", label: "viewer" },
  { value: "editor", label: "editor" },
  { value: "admin", label: "admin" },
  { value: "owner", label: "owner" },
];

type SortColumn = "name" | "role" | "status" | "lastSeenAt";
type SortDir = "asc" | "desc";

type PendingAction = {
  intent: "cycleRole" | "toggleStatus";
  userId: string;
  userName: string;
  description: string;
  tone: "danger" | "warning" | "default";
};

const roleOrder: Record<string, number> = {
  owner: 0,
  admin: 1,
  editor: 2,
  viewer: 3,
};

function getNextRole(current: Role): Role {
  const roles: Role[] = ["viewer", "editor", "admin", "owner"];
  const idx = roles.indexOf(current);
  return roles[(idx + 1) % roles.length] ?? "viewer";
}

function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(value));
}

function SortIcon({ active, dir }: { active: boolean; dir: SortDir }) {
  if (!active) return <span className="opacity-30">↕</span>;
  return <span>{dir === "asc" ? "↑" : "↓"}</span>;
}

function SortableHeader({
  col,
  current,
  dir,
  label,
  onSort,
}: {
  col: SortColumn;
  current: SortColumn;
  dir: SortDir;
  label: string;
  onSort: (col: SortColumn) => void;
}) {
  const isActive = current === col;
  return (
    <th className="px-4 py-3 font-medium">
      <button
        className={`flex items-center gap-1 text-left transition-colors hover:text-[var(--foreground)] ${
          isActive ? "text-[var(--foreground)]" : "text-[var(--muted)]"
        }`}
        onClick={() => onSort(col)}
        type="button"
      >
        {label}
        <SortIcon active={isActive} dir={dir} />
      </button>
    </th>
  );
}

export async function loader({ request }: Route.LoaderArgs) {
  await requireAuthSession(request);
  const users = await listDemoUsers();

  return {
    users: users.map(mapDbUserToDemoUser),
  };
}

export async function action({ request }: Route.ActionArgs) {
  const session = await requireAuthSession(request);
  const formData = await request.formData();
  const rawInput = Object.fromEntries(formData.entries());
  const parsed = usersActionSchema.safeParse(rawInput);

  if (!parsed.success) {
    return errorPayload(
      "BAD_REQUEST",
      parsed.error.issues[0]?.message ?? "Invalid request payload.",
    );
  }

  if (parsed.data.intent === "createUser") {
    const parsedCreate = createUserInputSchema.safeParse(parsed.data);
    if (!parsedCreate.success) {
      return errorPayload(
        "BAD_REQUEST",
        parsedCreate.error.issues[0]?.message ?? "Invalid user payload.",
      );
    }

    assertCanCreateUser(session.user, parsedCreate.data.role);

    const created = await createDemoUser({
      name: parsedCreate.data.name,
      username: parsedCreate.data.username,
      role: parsedCreate.data.role,
      passwordHash: hashPassword(parsedCreate.data.password),
      mustChangePassword: true,
    });

    if (!created) {
      return errorPayload("BAD_REQUEST", "Unable to create user. Username may already exist.");
    }

    await recordAuditEvent({
      actorId: session.user.id,
      action: "Created",
      target: `user ${created.username}`,
      details: `${session.user.username} created ${created.username} (${created.role})`,
    });

    return {
      ok: true,
      message: "User created. Password rotation is required on first sign-in.",
      intent: "createUser" as const,
    };
  }

  const current = await getDemoUserById(parsed.data.userId);
  if (!current) {
    return errorPayload("NOT_FOUND", "User not found.");
  }

  assertCanMutateUser(
    session.user,
    { id: current.id, role: toRole(current.role) },
    parsed.data.intent,
  );

  if (parsed.data.intent === "cycleRole") {
    const role = nextRole(toRole(current.role));

    if (session.user.role === "admin" && (role === "owner" || role === "admin")) {
      return errorPayload("FORBIDDEN", "Admin accounts can only assign viewer/editor roles.");
    }

    await updateDemoUserRole({ userId: parsed.data.userId, role });

    await recordAuditEvent({
      actorId: session.user.id,
      action: "Updated",
      target: `${current.username} role`,
      details: `${session.user.username} changed role to ${role}`,
    });

    return { ok: true, message: "Role updated.", intent: "cycleRole" as const };
  }

  const nextActive = !current.active;
  await updateDemoUserStatus({ userId: parsed.data.userId, active: nextActive });

  await recordAuditEvent({
    actorId: session.user.id,
    action: nextActive ? "Activated" : "Suspended",
    target: current.username,
    details: `${session.user.username} set status to ${nextActive ? "active" : "suspended"}`,
  });

  return { ok: true, message: "Status updated.", intent: "toggleStatus" as const };
}

export default function UsersRoute({ loaderData, actionData }: Route.ComponentProps) {
  const { users } = loaderData;

  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [role, setRole] = useState<Role>("viewer");
  const [search, setSearch] = useState("");
  const [sortColumn, setSortColumn] = useState<SortColumn>("name");
  const [sortDir, setSortDir] = useState<SortDir>("asc");
  const [pendingAction, setPendingAction] = useState<PendingAction | null>(null);

  const navigation = useNavigation();
  const isSubmitting = navigation.state === "submitting";
  const isLoading = navigation.state === "loading";
  const submit = useSubmit();
  const { addToast } = useToast();

  useEffect(() => {
    if (!actionData) return;
    if ("ok" in actionData && actionData.ok) {
      addToast(actionData.message, "success");
      if (actionData.intent === "createUser") {
        setName("");
        setUsername("");
        setPassword("");
        setConfirmPassword("");
        setRole("viewer");
      }
    } else if ("error" in actionData) {
      addToast(actionData.error.message, "error");
    }
  }, [actionData, addToast]);

  function handleSort(col: SortColumn) {
    if (sortColumn === col) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortColumn(col);
      setSortDir("asc");
    }
  }

  function requestAction(user: DemoUser, intent: "cycleRole" | "toggleStatus") {
    if (intent === "cycleRole") {
      const next = getNextRole(user.role);
      setPendingAction({
        intent,
        userId: user.id,
        userName: user.name,
        description: `Change ${user.name}'s role from ${user.role} to ${next}.`,
        tone: "default",
      });
    } else {
      const willSuspend = user.status === "active";
      setPendingAction({
        intent,
        userId: user.id,
        userName: user.name,
        description: willSuspend
          ? `Suspend ${user.name}'s account. They will lose access immediately.`
          : `Activate ${user.name}'s account and restore access.`,
        tone: willSuspend ? "danger" : "default",
      });
    }
  }

  function handleConfirm() {
    if (!pendingAction) return;
    submit({ intent: pendingAction.intent, userId: pendingAction.userId }, { method: "post" });
    setPendingAction(null);
  }

  const filteredUsers = useMemo(() => {
    if (!search.trim()) return users;
    const q = search.toLowerCase();
    return users.filter(
      (u) =>
        u.name.toLowerCase().includes(q) ||
        u.username.toLowerCase().includes(q) ||
        u.role.toLowerCase().includes(q) ||
        u.status.toLowerCase().includes(q),
    );
  }, [users, search]);

  const sortedUsers = useMemo(() => {
    return [...filteredUsers].sort((a, b) => {
      const dir = sortDir === "asc" ? 1 : -1;
      if (sortColumn === "name") return a.name.localeCompare(b.name) * dir;
      if (sortColumn === "role") {
        return ((roleOrder[a.role] ?? 4) - (roleOrder[b.role] ?? 4)) * dir;
      }
      if (sortColumn === "status") return a.status.localeCompare(b.status) * dir;
      if (sortColumn === "lastSeenAt") {
        return (new Date(a.lastSeenAt).getTime() - new Date(b.lastSeenAt).getTime()) * dir;
      }
      return 0;
    });
  }, [filteredUsers, sortColumn, sortDir]);

  return (
    <section>
      <SectionHeader
        caption="User Management"
        description="Server-side validation and authorization are enforced for every mutation."
        title="Team Access Controls"
      />

      <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_1.5fr]">
        <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4">
          <p className="text-sm font-medium">Create User</p>
          <p className="mt-2 text-sm text-[var(--muted)]">
            Owner/admin accounts can provision users directly with a temporary password.
          </p>
          <p className="mt-1 text-xs text-[var(--muted)]">{AUTH_PASSWORD_POLICY_MESSAGE}</p>
          <Form className="mt-3 grid gap-3" method="post">
            <input name="intent" type="hidden" value="createUser" />
            <InputField
              label="Name"
              name="name"
              onChange={(event) => setName((event.target as HTMLInputElement).value)}
              required
              value={name}
            />
            <InputField
              label="Username"
              name="username"
              onChange={(event) => setUsername((event.target as HTMLInputElement).value)}
              required
              value={username}
            />
            <SelectField
              label="Role"
              name="role"
              onChange={(event) => setRole((event.target as HTMLSelectElement).value as Role)}
              options={roleOptions}
              value={role}
            />
            <InputField
              autoComplete="new-password"
              label="Temporary Password"
              minLength={AUTH_PASSWORD_MIN_LENGTH}
              name="password"
              onChange={(event) => setPassword((event.target as HTMLInputElement).value)}
              required
              type="password"
              value={password}
            />
            <InputField
              autoComplete="new-password"
              label="Confirm Password"
              minLength={AUTH_PASSWORD_MIN_LENGTH}
              name="confirmPassword"
              onChange={(event) => setConfirmPassword((event.target as HTMLInputElement).value)}
              required
              type="password"
              value={confirmPassword}
            />
            <Button disabled={isSubmitting} type="submit">
              Create User
            </Button>
          </Form>
        </article>

        <div className="grid gap-3">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm text-[var(--muted)]">
              {sortedUsers.length} of {users.length} users
            </p>
            <input
              className="w-full max-w-xs rounded-lg border border-[var(--border)] bg-[var(--overlay)] px-3 py-1.5 text-sm outline-none transition-colors placeholder:text-[var(--muted)] focus:border-[var(--accent)] focus:ring-1 focus:ring-[var(--accent)]"
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search users..."
              type="search"
              value={search}
            />
          </div>

          {sortedUsers.length === 0 && !isLoading ? (
            <EmptyState
              description={
                search ? "Try a different search term." : "Create a user to get started."
              }
              title={search ? "No users match your search" : "No users yet"}
            />
          ) : (
            <article className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
              <table className="w-full border-collapse text-left text-sm">
                <thead>
                  <tr className="border-b border-[var(--border)]">
                    <th className="px-4 py-3 font-medium text-[var(--muted)]" />
                    <SortableHeader
                      col="name"
                      current={sortColumn}
                      dir={sortDir}
                      label="User"
                      onSort={handleSort}
                    />
                    <SortableHeader
                      col="role"
                      current={sortColumn}
                      dir={sortDir}
                      label="Role"
                      onSort={handleSort}
                    />
                    <SortableHeader
                      col="status"
                      current={sortColumn}
                      dir={sortDir}
                      label="Status"
                      onSort={handleSort}
                    />
                    <SortableHeader
                      col="lastSeenAt"
                      current={sortColumn}
                      dir={sortDir}
                      label="Last Seen"
                      onSort={handleSort}
                    />
                    <th className="px-4 py-3 font-medium text-[var(--muted)]">Created</th>
                  </tr>
                </thead>
                <tbody>
                  {isLoading
                    ? Array.from({ length: 5 }).map((_, i) => (
                        <tr
                          className="border-b border-[var(--border)]"
                          // biome-ignore lint/suspicious/noArrayIndexKey: skeleton placeholders
                          key={i}
                        >
                          <td className="px-4 py-3">
                            <Skeleton className="size-9 rounded-full" />
                          </td>
                          <td className="px-4 py-3">
                            <Skeleton className="mb-1 h-4 w-24" />
                            <Skeleton className="h-3 w-32" />
                          </td>
                          <td className="px-4 py-3">
                            <Skeleton className="h-5 w-14 rounded-full" />
                          </td>
                          <td className="px-4 py-3">
                            <Skeleton className="h-5 w-16 rounded-full" />
                          </td>
                          <td className="px-4 py-3">
                            <Skeleton className="h-3 w-20" />
                          </td>
                          <td className="px-4 py-3">
                            <Skeleton className="h-3 w-20" />
                          </td>
                        </tr>
                      ))
                    : sortedUsers.map((user) => (
                        <tr
                          className="row-interactive border-b border-[var(--border)]"
                          key={user.id}
                        >
                          <td className="px-4 py-3 align-middle">
                            <Link to={`/users/${user.id}`}>
                              <Avatar name={user.name} size="md" />
                            </Link>
                          </td>
                          <td className="px-4 py-3 align-top">
                            <Link to={`/users/${user.id}`}>
                              <p className="font-medium transition-colors hover:text-[var(--accent)]">
                                {user.name}
                              </p>
                              <p className="text-xs text-[var(--muted)]">@{user.username}</p>
                              {user.mustChangePassword ? (
                                <p className="text-xs text-[var(--tone-warning-fg)]">
                                  Password update required
                                </p>
                              ) : null}
                            </Link>
                          </td>
                          <td className="px-4 py-3 align-top">
                            <button
                              className="cursor-pointer"
                              onClick={() => requestAction(user, "cycleRole")}
                              type="button"
                            >
                              <Badge variant={roleBadgeVariant(user.role)}>{user.role}</Badge>
                            </button>
                          </td>
                          <td className="px-4 py-3 align-top">
                            <button
                              className="cursor-pointer"
                              onClick={() => requestAction(user, "toggleStatus")}
                              type="button"
                            >
                              <Badge variant={statusBadgeVariant(user.status)}>{user.status}</Badge>
                            </button>
                          </td>
                          <td className="px-4 py-3 align-top text-[var(--muted)]">
                            {formatTimestamp(user.lastSeenAt)}
                          </td>
                          <td className="px-4 py-3 align-top text-xs text-[var(--muted)]">
                            {formatTimestamp(user.createdAt)}
                          </td>
                        </tr>
                      ))}
                </tbody>
              </table>
            </article>
          )}
        </div>
      </div>

      <ConfirmDialog
        description={pendingAction?.description ?? ""}
        onCancel={() => setPendingAction(null)}
        onConfirm={handleConfirm}
        open={pendingAction !== null}
        title={
          pendingAction?.intent === "cycleRole"
            ? `Change role for ${pendingAction.userName}`
            : `Update status for ${pendingAction?.userName ?? ""}`
        }
        tone={pendingAction?.tone ?? "default"}
      />
    </section>
  );
}

// apps/web-demo/pages/users/index.vue
<script setup lang="ts">
definePageMeta({ middleware: "require-auth" });

type UserRow = {
  id: string;
  name: string;
  username: string;
  role: "owner" | "admin" | "editor" | "viewer";
  status: "active" | "suspended";
  mustChangePassword: boolean;
  createdAt: string;
  lastSeenAt: string;
};

const { data, refresh: refreshUsers } = await useFetch<{
  ok: boolean;
  users: UserRow[];
  error?: { message: string };
}>("/api/users", {
  headers: process.server ? useRequestHeaders(["cookie"]) : undefined,
});

const createForm = reactive({
  name: "",
  username: "",
  role: "viewer",
  password: "",
  confirmPassword: "",
});

const search = ref("");
const feedback = ref<{ message: string; error: boolean } | null>(null);
const loadingAction = ref(false);

const users = computed(() => (data.value?.ok ? data.value.users : []));

const filteredUsers = computed(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return users.value;

  return users.value.filter(
    (user) =>
      user.name.toLowerCase().includes(q) ||
      user.username.toLowerCase().includes(q) ||
      user.role.toLowerCase().includes(q) ||
      user.status.toLowerCase().includes(q),
  );
});

function roleTone(role: UserRow["role"]) {
  return role;
}

async function createUser() {
  feedback.value = null;
  loadingAction.value = true;

  try {
    const result = await $fetch<{ ok: boolean; message?: string; error?: { message: string } }>(
      "/api/users",
      {
        method: "POST",
        body: createForm,
      },
    );

    if (!result.ok) {
      feedback.value = { message: result.error?.message ?? "Unable to create user.", error: true };
      return;
    }

    feedback.value = { message: result.message ?? "User created.", error: false };
    createForm.name = "";
    createForm.username = "";
    createForm.role = "viewer";
    createForm.password = "";
    createForm.confirmPassword = "";
    await refreshUsers();
  } catch (error: unknown) {
    feedback.value = { message: getApiErrorMessage(error, "Unable to create user."), error: true };
  } finally {
    loadingAction.value = false;
  }
}

async function cycleRole(userId: string) {
  loadingAction.value = true;
  try {
    const result = await $fetch<{ ok: boolean; message?: string; error?: { message: string } }>(
      `/api/users/${userId}/cycle-role`,
      {
        method: "POST",
      },
    );
    feedback.value = {
      message: result.ok
        ? (result.message ?? "Role updated.")
        : (result.error?.message ?? "Role update failed."),
      error: !result.ok,
    };
    await refreshUsers();
  } catch (error: unknown) {
    feedback.value = { message: getApiErrorMessage(error, "Role update failed."), error: true };
  } finally {
    loadingAction.value = false;
  }
}

async function toggleStatus(userId: string) {
  loadingAction.value = true;
  try {
    const result = await $fetch<{ ok: boolean; message?: string; error?: { message: string } }>(
      `/api/users/${userId}/toggle-status`,
      {
        method: "POST",
      },
    );
    feedback.value = {
      message: result.ok
        ? (result.message ?? "Status updated.")
        : (result.error?.message ?? "Status update failed."),
      error: !result.ok,
    };
    await refreshUsers();
  } catch (error: unknown) {
    feedback.value = { message: getApiErrorMessage(error, "Status update failed."), error: true };
  } finally {
    loadingAction.value = false;
  }
}
</script>

<template>
  <section>
    <SectionHeader
      caption="User Management"
      title="Team Access Controls"
      description="Create users, rotate roles, and suspend access with server-enforced authorization rules."
    />

    <div class="mt-5 grid gap-4 lg:grid-cols-[1fr_1.6fr]">
      <article class="data-card">
        <p class="text-sm font-medium">Create User</p>
        <form class="mt-3 grid gap-3" @submit.prevent="createUser">
          <input v-model="createForm.name" class="input" placeholder="Display name" required type="text" />
          <input v-model="createForm.username" class="input" placeholder="username" required type="text" />
          <select v-model="createForm.role" class="input">
            <option value="viewer">viewer</option>
            <option value="editor">editor</option>
            <option value="admin">admin</option>
            <option value="owner">owner</option>
          </select>
          <input v-model="createForm.password" class="input" minlength="8" placeholder="Password" required type="password" />
          <input
            v-model="createForm.confirmPassword"
            class="input"
            minlength="8"
            placeholder="Confirm password"
            required
            type="password"
          />
          <button class="btn btn-primary" :disabled="loadingAction" type="submit">Create User</button>
        </form>
      </article>

      <article class="data-card overflow-x-auto">
        <div class="mb-3 flex items-center gap-2">
          <input v-model="search" class="input" placeholder="Search users..." type="search" />
          <button class="btn btn-muted" type="button" @click="refreshUsers()">Refresh</button>
        </div>

        <table class="table min-w-[620px]">
          <thead>
            <tr>
              <th>Name</th>
              <th>Role</th>
              <th>Status</th>
              <th>Last Seen</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="user in filteredUsers" :key="user.id">
              <td>
                <NuxtLink class="font-medium hover:underline" :to="`/users/${user.id}`">{{ user.name }}</NuxtLink>
                <p class="text-xs text-[var(--muted)]">@{{ user.username }}</p>
              </td>
              <td>
                <BadgePill :tone="roleTone(user.role)">{{ user.role }}</BadgePill>
              </td>
              <td>
                <BadgePill :tone="user.status === 'active' ? 'success' : 'warning'">{{ user.status }}</BadgePill>
              </td>
              <td class="text-xs text-[var(--muted)]">{{ new Date(user.lastSeenAt).toLocaleString() }}</td>
              <td>
                <div class="flex flex-wrap gap-2">
                  <button class="btn btn-muted" :disabled="loadingAction" type="button" @click="cycleRole(user.id)">
                    Cycle Role
                  </button>
                  <button class="btn" :class="user.status === 'active' ? 'btn-danger' : 'btn-muted'" :disabled="loadingAction" type="button" @click="toggleStatus(user.id)">
                    {{ user.status === "active" ? "Suspend" : "Activate" }}
                  </button>
                </div>
              </td>
            </tr>
            <tr v-if="!filteredUsers.length">
              <td class="text-sm text-[var(--muted)]" colspan="5">No users found.</td>
            </tr>
          </tbody>
        </table>
      </article>
    </div>

    <p v-if="feedback" class="mt-3 text-sm" :class="feedback.error ? 'text-[var(--tone-error-fg)]' : 'text-[var(--tone-success-fg)]'">
      {{ feedback.message }}
    </p>
  </section>
</template>
